name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.run_number }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force

      - name: Debug paths
        run: |
          echo "Workspace: ${{ github.workspace }}"
          ls -l ${{ github.workspace }}

      - name: Wait for GitHub Pages
        run: |
          sleep 30
      - name: Build ZIM from published site
        run: |
          mkdir -p docs/zim
          docker pull ghcr.io/openzim/zimit
          docker run --rm \
            -v $PWD/docs/zim:/output \
            --shm-size=1gb \
            ghcr.io/openzim/zimit \
            zimit \
              --seeds https://deyan.is-a.dev/Zephyr \
              --output /output \
              --name ZephyrDocs.zim
          ls -l docs/zim

      - name: Upload ZIM artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-zim
          path: docs/ZephyrDocs.zim